# Generated by Django 3.1 on 2024-03-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='userprofile/default.jpg', upload_to='userprofile'),
        ),
    ]
