# Generated by Django 3.1 on 2024-03-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_urlSlug',
            field=models.SlugField(max_length=128, unique=True),
        ),
    ]
